### ISSUE TITLE
Font for highlighted incorrect answer too big

### ISSUE THREAD

**Issue by wfaulk** [kebernet/shortyz#1]
If Shortyz is set to show errors, and an error is highlighted — that is, in a selected row or column — it displays as red text on an orange background. As of this most recent version, the font is too large in this circumstance.

**Comment by wfaulk** [comment]
The font is also too large if the errored box is the currently selected box, except that the font is white in that case.

**Comment by wfaulk** [comment]
![screenshot_2015-09-01-04-31-35](https://cloud.githubusercontent.com/assets/205470/9599698/f215d140-5063-11e5-9c8e-7c29693686ce.png)

**Comment by kebernet** [comment]
Fixed in 4.1.1.
