### ISSUE TITLE
It started downloading LA Times puzzles from 2018

### ISSUE THREAD

**Issue by simzacks** [kebernet/shortyz#173]
A couple days ago the LA Times puzzles that are downloaded are from the current date, but from 2018. The USA Today puzzle still downloads the current days puzzle. 
Apr 3 & 4 were correct. There was no puzzle downloaded Apr 5 and Apr 6 & 7 both show 2018

When I click the download button and choose a date,  the year is set correctly to 2021.

**Comment by tperki** [comment]
Confirmed, same issue here. No LAT 4/5 and 6, puzzle from 2018 on 4/7. Update: the puz files are up on Cruciverb - I can download and open manually. Also, other puzzle apps behave the same - open 2018 puzzles that is.

**Comment by simzacks** [comment]
Resolved

**Comment by jgok** [comment]
This issue started occurring again this week (Apr 26-28, 2021)
