### ISSUE TITLE
Unable to Download Many Puzzles since October 18, 2022

### ISSUE THREAD

**Issue by wcole2551** [kebernet/shortyz#188]
I've been unable to download many puzzles from Shortyz on my Android since October 18, 2022.  Specifically I can't download Universal Crossword.  I am still able to download Newsday and Jonesin' Crosswords.  Hoping someone can check to see what has gone wrong.

**Comment by hillacinth** [comment]
Similar problem...I was enjoying Shortyz as a recent new user, but as of November 19th no new puzzles are downloading. It's an Android phone. The phone looks like it is trying to download puzzles, but none appear in the app.

**Comment by dtoxic47** [comment]
same thing here also A11 S10+,also is there a way to download version 31? that one was most stable for me

**Comment by wcole2551** [comment]
My Universal Puzzle (and others like USA Today) started downloading again on November 23, 2022.  Thanks to whoever checked into this issue and got the puzzles downloading again.  Wes
