### ISSUE TITLE
Incorrect cells no longer appear red

### ISSUE THREAD

**Issue by eevee** [kebernet/shortyz#24]
With "Show errors" turned on, there's currently no visual difference between an incorrect cell and a correct cell that _used to_ be incorrect.  Both have black text on a pink background.  If the word is highlighted, _then_ the text shows in red.

The result is that I've had a fully-filled crossword with a single incorrect letter and had to tap around methodically until I found out which one it was.  :)

I think this is since Shortyz 4.1.1.  I'm on Android 6.0.  Related to #1, maybe?

**Comment by andrewgaul** [comment]
@eevee Can you retest with the latest release?

**Comment by eevee** [comment]
@andrewgaul Seems to be fixed now, yes, thank you!
