### ISSUE TITLE
Joseph Crosswords autoscaling incorrectly

### ISSUE THREAD

**Issue by lubarb** [kebernet/shortyz#26]
With my tablet locked in portrait mode, Joseph Crosswords scale larger than they should, and are overlapped by the keyboard.

The crosswords are non-square, and it looks like they may scale for the smaller width rather than the height.

**Comment by andrewgaul** [comment]
@lubarb Can you test with the latest release?  #49 duplicates this issue and 40c85688348ec4cc6eabaa450f317fda7d963352 addresses it.

**Comment by lubarb** [comment]
Joseph crosswords now work fine for me with 4.20 on my shield tablet. I
always use it in portrait lock mode, but it also appears correctly in
landscape.

Thanks!

Luther
