### ISSUE TITLE
"stop at end" + "skip filled boxes" acts incorrectly for words that end at the edge of the puzzle

### ISSUE THREAD

**Issue by benkehoe** [kebernet/shortyz#4]
This happens when the movement style is "stop at end" and "skip filled boxes" is checked, and you have a word with some letters at the end filled in (e.g., CRO_SW_RD). If you fill in the S, the cursor will correctly skip to the next open slot. If the word does *not* end at the edge of the puzzle (i.e., there is a black square after the D), filling in the O does not move the cursor. I believe this to be the intended behavior. However, if the end of the word is at the edge of the puzzle, filling the O will cause the cursor to skip to the end of the word (i.e., the D).

**Comment by rappazzo** [comment]
I have a fix for this issue, and I will put in a pull request shortly.

**Comment by kebernet** [comment]
Lurve PRs. 

Fixed in 4.1.1/
