### ISSUE TITLE
F-Droid out of date

### ISSUE THREAD

**Issue by gaul** [kebernet/shortyz#41]
Can you work with F-Droid to update its Shortyz version from 3.2.10 to the latest?  They rejected 4.0.7 due to its dependency on Play Services:
- https://f-droid.org/wiki/page/com.totsp.crossword.shortyz
- https://f-droid.org/forums/topic/shortyz-crossword-puzzles/

**Comment by yourealwaysbe** [comment]
I have created a [merge request](https://github.com/yourealwaysbe/play-services-shortyz) to include the latest version of Shortyz.  This has required some hacking on my part to strip out Play Services and Crashlytics/Fabric.

@kebernet have you considered a "foss" build flavour that does not use closed-source libraries (and omits crashlytics user tracking)?  I am willing to help with this.

Btw, the materialpreference library is [deprecated](https://github.com/yourealwaysbe/play-services-shortyz) and jenzz recommends using the android support libraries instead (see link).

**Comment by gaul** [comment]
@yourealwaysbe Thanks for addressing this issue!  It would be great to include your foss changes in mainline code, perhaps as a separate gradle file?
