### ISSUE TITLE
NY Times puzzles no longer downloading

### ISSUE THREAD

**Issue by cgales** [kebernet/shortyz#64]
Starting this Monday (Aug. 22), the NYT puzzle will not download.

**Comment by kebernet** [comment]
I have not had a problem. Can you double check you subscription state (ie, can you DL the puzzle from the NYT website from the browser?)

**Comment by cgales** [comment]
Hi, thanks for checking...it is now working for me again, after two and a
half days of silence. Maybe checking in the browser woke it up again. :-)
