### ISSUE TITLE
Feature request - Kryptics

### ISSUE THREAD

**Issue by cfken** [kebernet/shortyz#76]
The 'Show Errors' and 'Reveal' menu options are disabled for Kryptics. Is that intentional? If not, enabling them would be an enhancement in my opinion. I sometimes need the help. ;-)

Thx

**Comment by kebernet** [comment]
"Show errors" and "Reveal" are available for puzzles that have the answers in the puzzle file. If the answers aren't there, they are disabled. I don't control the puzzle files. :P

**Comment by cfken** [comment]
OK. Thanks for the prompt response.Somehow, when I download Kegler's using Chrome, and open in Shortyz, those functions work. It doesn't work with any other browser - at least that I can find. Maybe Shortyz is grabbing a different version?Anyway, thanks for the app. I use it daily.KenOn Jan 9, 2017 10:09 AM, kebernet <notifications@github.com> wrote:"Show errors" and "Reveal" are available for puzzles that have the answers in the puzzle file. If the answers aren't there, they are disabled. I don't control the puzzle files. :P
