### ISSUE TITLE
NY Times puzzles have stopped downloading

### ISSUE THREAD

**Issue by rdeits** [kebernet/shortyz#98]
As of today, I can't seem to download the NY times crossword. Attempting to download a puzzle in shortyz brings up the normal download notification, but the puzzle never shows up in the list. 

So far I have tried:

* verifying on nytimes.com that my subscription is still active and that I can download crosswords from their site
* re-entering my nytimes email and password inside shortyz
* restarting the app
* restarting my phone

but to no avail. Other crossword sources appear to be working fine through the app, just not NYT. I'm using Shortyz 4.3.8 on a Nexus 5X. 

I realize that "it doesn't work" is a pretty tough issue to debug remotely. Is there any additional log information I can access to try to narrow down why this is happening?

**Comment by wfaulk** [comment]
It's not working for me, either.

**Comment by mattneft** [comment]
I'm having this issue too.  

Shortyz 4.3.8
Samsung Galaxy S5
Android 6.0.1

**Comment by ljarin** [comment]
Same

**Comment by kebernet** [comment]
Hey everyone. Yeah. It is broken.

The NYT has added Google Captcha to their myaccount login page and Shortyz is no longer able to log in to download the puzzles. I spent some time tonight trying to come up with a workaround, but it was a completely fail. 

I am going to look into setting up a way to do a proper browser-based login this weekend, but it is going to take me, at best, a few days.

**Comment by jimbeard2** [comment]
Not the first time Nytimes has spoiled my fun.  (It used to burn through the battery for some money related reason. )

**Comment by mamsterla** [comment]
I have to report the same. Verified my account info as well.

**Comment by kebernet** [comment]
Fix is in the Play Store. If you just hit the "Download" button, it should prompt you to go through the new web-based login.

**Comment by rdeits** [comment]
Thank you!

**Comment by jimbeard2** [comment]
Thank you.   Much appreciated.

**Comment by MGD1981** [comment]
I have been having this exact same issue for the past week. Have they changed their login procedure again?
